spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 自动根据代码创建/更新数据库表，开发阶段用这个
    show-sql: true          # 在控制台打印 SQL，方便调试

server:
  port: 8080